### PR TITLE
Fast matcher etc.: "Cosmetic" changes

### PR DESCRIPTION
**Pull request by ampli**
1. In the previous change I added match-list push/get functions, but forgot to change the a description and use the "get" function in two places in which the match-list array was directly accessed.
2. Also included here old-typo fixes which I found while working on these files.

### CODE REVIEW

**Comment by linas** [comment]
code did seem to work without these changes!?

**Comment by linas** [comment]
p.s. plan to publish 5.3.3 today or tomorrow let me know if I should wait.

**Comment by ampli** [comment]
> code did seem to work without these changes!?

They are all cosmetic...

> p.s. plan to publish 5.3.3 today or tomorrow let me know if I should wait.

No need to wait.

I'm working now on an initial and ad-hoc multi-suffix split function, but it will take several days more at least, and meanwhile I postpone all the other LG work until I finish it. (I say  "initial and ad-hoc" because I have a wider plan for general tokenization, which I started to implement but it will take some more (unknown) time.)

**Comment by linas** [comment]
OK 5.3.3 is out. I'm not announcing on mailing list though.

**Pull request merged**
