### PR TITLE
Fix problems indicated in issue #652

### PR DESCRIPTION
**Pull request by ampli**
Solve the main problems pointed out in issue #652.
In the same occasion, add several more clean ups.

### CODE REVIEW

**Comment by ampli** [comment]
@linas, I see you meanwhile made some changes that conflict with my changes here...
I will resolve these conflicts  and push this PR again....

**Comment by ampli** [comment]
I resolved the conflict.

**Comment by linas** [comment]
Thanks!  I think I'm done hacking on the source for a while.

**Comment by ampli** [comment]
I have some big efficiency changes (still need last polishing) that I hope you will find time to review...

**Comment by linas** [comment]
yes, I know :-)

**Pull request merged**
