### PR TITLE
Travis testing support

### PR DESCRIPTION
**Pull request by AmeBel**
Some issues that need to be resolved.
 - The tests don't give non-zero exit code as such the badge isn't useful for evaluating pull-requests
 - The bindings are not tested.

Not sure how to proceed. Any suggestions?

### CODE REVIEW

**Comment by ampli** [comment]
Currently the Travis tests always fail with this:
```
WARNING: We were unable to find a .travis.yml file. This may not be what you
  want. Build will be run with default settings.
```
Until recently this failure didn't happen.
What is the reason for that?
Can I do something in this regard?

--
Regarding the proposed changes:
The 4.0.*batch files are not really good for this automatic test.
Instead, the following should be used:
```
../configure --with-python-bindings
...
make check
```

**Comment by AmeBel** [comment]
I am getting the following error
```
../configure: line 16677: syntax error near unexpected token `LIBGC,'
../configure: line 16677: `	PKG_CHECK_MODULES(LIBGC, bdw-gc, gc=yes, gc=no)'
```

**Comment by AmeBel** [comment]
Here is my dev-space https://github.com/AmeBel/link-grammar/blob/travis/docker/development/Dockerfile

**Comment by ampli** [comment]
You need to install also **pkg-config**.

**Comment by AmeBel** [comment]
@ampli updated as per your suggestion.

**Comment by linas** [comment]
Not gonna happen.

**Comment by ampli** [comment]
Can the travis invocation be removed?
It is just annoying to see the "all tests failed" messages and all of these red x's...

**Comment by AmeBel** [comment]
@ampli it is removed.

**Pull request closed without merging**
