### PR TITLE
link-grammar: add build patch

### PR DESCRIPTION
**Pull request by chenrui333**
Add build patch for 5.12.3 release build on macos

relates to https://github.com/Homebrew/homebrew-core/pull/134103

### CODE REVIEW

**Comment by linas** [comment]
Thanks! This will be included in version 5.12.4 to be published in a few weeks(?) maybe a few months.

**Comment by linas** [comment]
Actually, I'm going to rever the part that says `HAVE_MALLOC_TRIM` -- this is not set anywhere. That block of code is protected by `__GLIBC__` ... are you saying that MacOS is pretending to be glibc, without actually being glibc?

**Comment by linas** [comment]
I'm also confused by the `_WIN32` and not `__APPLE__` part -- are you saying that MacOS is pretnding to be WIN32 ??? that also seems kind of crazy, to me, but what do I know.  Anything is possible, I suppose ...

**Comment by chenrui333** [comment]
I can help with some macos CI work tomorrow (that would surface the build issue more easily)

**Pull request merged**
