### PR TITLE
Free kept_table on thread-exit

### PR DESCRIPTION
**Pull request by linas**
Some users of link-grammar create hundreds of thousands of threads.
The tables leaked RAM very quickly in this case.

### CODE REVIEW

**Comment by ampli** [comment]
The `pthread` related stuff should be protected by an `#ifdef` to prevent compilation break on MSVC.
One way to do that is to use [`AX_PTHREAD`](https://www.gnu.org/software/autoconf-archive/ax_pthread.html) in `configure` + `HAVE_PTHREAD`. It is further possible to use `AX_PTHREAD` to set `LIB` and `CFLAGS` etc., but I don't know how much it is important (besides for AIX, which may not be so important, so it may just be mentioned there as FIXME).
Note that `pthread` usage in `spellcheck-*.c` is already protected by `HAVE_*` that is not enabled on the MSVC build.

**Comment by linas** [comment]
the tss_create stuff is a part of the C11 ISO standard -- is MSVC not C11 compliant?

**Comment by ampli** [comment]
> the tss_create stuff is a part of the C11 ISO standard -- is MSVC not C11 compliant?

According to section 7.26 in the [C11 standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf), it is optional.

MSVC is mainly a C++ compiler, and its C11 compatibility is limited.
It doesn't support C11 threads (but it supports C++11 threads).

In any case, now that you use `AX_PTHREAD` you can just add `#if HAVE_PTHREAD`.
`

**Comment by linas** [comment]
Merging.

**Comment by ampli** [comment]
It seems there is some confusion regarding threads here.
This fix uses C11 threads, but checks for pthread, which is POSIX threads.
It just works on Linux because it has both.

I just tried to compile LG on OS-X (10.14, currently the latest release), and found that it has no `threads.h`. For some reason `clang` there also doesn't define `__STDC_NO_THREADS__` (like some other C compilers that don't have  `threads.h`). A similar problem may exist on MinGW and Cygwin, and in other compilers.

I also found that configure finds there (OS X) PTHREAD (so HAVE_PTHRAED==1), but this doesn't help in this regard.

I propose to check for the availability of the `threads.h` header file and then define `HAVE_THREADS_H=1`
I also propose to still check for PTHREAD and protect the pthread code in `spellcheck_*.c` with `HAVE_PTHREAD`.
If this looks fine I will send a PR.

**Comment by linas** [comment]
Sigh. Sounds fine.

**Comment by ampli** [comment]
Fixed in PR #1178.

**Pull request merged**
