### PR TITLE
Remove remains of corpus statistics and INFIX_NOTATION

### PR DESCRIPTION
**Pull request by ampli**
EDIT: This fixes also the broken language bindings.

### CODE REVIEW

**Comment by linas** [comment]
thanks!

**Comment by ampli** [comment]
Some corpus stats stuff still remained in `data/tools` and I didn't handle it.
Some of that can maybe converted to manipulate SQL dicts. 
I also found that `wiktionary.pl` needs updating to work fine. It can also be made much better.

**Comment by linas** [comment]
> data/tools

I completely forgot about that directory; haven't used the tools in many many years.  Anyway, I just now removed the cluster-tools. I probably should have remove `wiktionary.pl` but I didn't.  It was never used for anything. It's unusable in its current form - one cannot hand-check the 80K words in the English dict, and automation is unreliable due to the large number of exceptional cases.

**Comment by linas** [comment]
I removed wiktionary.pl just now.

**Pull request merged**
